#include <furi.h>
#include <input/input.h>
#include <stdlib.h>
#include <gui/gui.h>

/* generated by fbt from .png files in images folder */
#include <rfid_simulator_icons.h>
#include <furi_hal.h>
#include <furi_hal_resources.h>

#include <rfid_simulator.h>

static void input_callback(InputEvent* input_event, FuriMessageQueue* event_queue) {
    furi_assert(event_queue);

    PluginEvent event = {.type = EventTypeKey, .input = *input_event};
    furi_message_queue_put(event_queue, &event, 25);
}

static void render_callback(Canvas* const canvas, void* ctx) {
    PluginState* state = ctx;
    UNUSED(state);

    if(furi_mutex_acquire(state->mutex, 25) != FuriStatusOk) {
        FURI_LOG_E("TEST", "mutex acquire failed");
        return;
    }

    // border around the edge of the screen
    canvas_draw_frame(canvas, 0, 0, 128, 64);
    canvas_set_font(canvas, FontPrimary);
    canvas_draw_str_aligned(canvas, state->x, state->y, AlignCenter, AlignCenter, "Hello World!");

    if(furi_mutex_release(state->mutex) != FuriStatusOk) {
        FURI_LOG_E("TEST", "mutex release failed");
    }
}

static void main_loop(ViewPort* view_port, FuriMessageQueue* event_queue, PluginState* state) {
    PluginEvent event;

    for(bool processing = true; processing;) {
        FuriStatus event_status = furi_message_queue_get(event_queue, &event, 100);

        // FuriStatus event_status = furi_message_queue_put(event_queue, &event, 100);
        // if(furi_mutex_acquire(state->mutex, 25) != FuriStatusOk) {
        //     FURI_LOG_E("TEST", "mutex acquire failed");
        //     return;
        // }

        if(event_status == FuriStatusOk) {
            // press events
            if(event.type == EventTypeKey) {
                if(event.input.type == InputTypeLong) {
                    switch(event.input.key) {
                    case InputKeyBack:
                        processing = false;
                        break;
                    default:
                        break;
                    }
                } else if(event.input.type == InputTypePress) {
                    switch(event.input.key) {
                    case InputKeyUp:
                        state->y -= 1;
                        break;
                    case InputKeyDown:
                        state->y += 1;
                        break;
                    case InputKeyRight:
                        state->x += 1;
                        break;
                    case InputKeyLeft:
                        state->x -= 1;
                        break;
                    default:
                        break;
                    }
                }
            }
        } else {
            FURI_LOG_D("TEST", "FuriMessageQueue: event timeout");
            // event timeout
        }

        // if(furi_mutex_release(state->mutex) != FuriStatusOk) {
        //     FURI_LOG_E("TEST", "mutex release failed");
        // }

        view_port_update(view_port);
    }
}

int32_t rfid_simulator_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm rfid_simulator!");

    FuriMessageQueue* event_queue = furi_message_queue_alloc(8, sizeof(PluginEvent));

    // State initialization
    PluginState* state = malloc(sizeof(PluginState));
    state->x = 64;
    state->y = 32;

    if(!(state->mutex = furi_mutex_alloc(FuriMutexTypeNormal))) {
        FURI_LOG_E("Hello_world", "cannot create mutex\r\n");
        free(state);
        return 255;
    }

    // Set system callbacks
    ViewPort* view_port = view_port_alloc();
    view_port_draw_callback_set(view_port, render_callback, state);
    view_port_input_callback_set(view_port, input_callback, event_queue);

    // Open GUI and register view_port
    Gui* gui = furi_record_open("gui");
    gui_add_view_port(gui, view_port, GuiLayerFullscreen);

    // Start main loop
    main_loop(view_port, event_queue, state);

    // Cleanup
    view_port_enabled_set(view_port, false);
    gui_remove_view_port(gui, view_port);
    furi_record_close("gui");
    view_port_free(view_port);
    furi_message_queue_free(event_queue);
    furi_mutex_free(state->mutex);

    return 0;
}
